### ISSUE TITLE
How to customize handleItemClick?

### ISSUE THREAD

**Issue by HorseBinky** [ABASystems/react-keyed-file-browser#4]
Hello!
So I managed to replace the fileRenderer with my React Component. But I'm still struggling to custom the onClick Event on the file.
I want to pass my function as props to the FileBrowser to get the key of the clicked file to use it in my app.
Any suggestions how I can pass the function?

Thanks!!

**Comment by ryanarmstrong** [comment]
Yea wondering the same here

**Comment by francois06** [comment]
bump

**Comment by jarekwg** [comment]
Hey, sorry for the 6 month wait on a response.

I believe I've addressed this in d0e9bf0824ef89bde2b3a1123bebf696a7108ea8
Please advise if that doesn't solve the problem and I'll reopen the issue.
