### ISSUE TITLE
Deleting folder and creating new folder causes old folder to appear

### ISSUE THREAD

**Issue by gregorianisch** [ABASystems/react-keyed-file-browser#7]
Hi,

there is a bug with folders. 

**Steps to reproduce:**
1 - Delete existing folder
2 - Click add new folder

**Result:**
New folder appears with old folder name, clicking on it makes it disappear. When clicking new folder again and clicking outside folder area causes old folder to disappear. After that clicking on new folder causes new folder to appear.

**Expected result:**
After deleting old folder it is possible to create new folder instantly and deleted folder no longer appears.

**Comment by jarekwg** [comment]
Thanks for reporting. Will investigate.

**Comment by jarekwg** [comment]
Fixed in 26b3f6c53cad1ef164924b260ff7a19808e0a3c2

**Comment by gregorianisch** [comment]
@jarekwg Thanks, but after this update it's not possible to add folder at all.

Error when clicking "Add Folder":
`Uncaught TypeError: Cannot read property 'value' of undefined`

**Comment by jarekwg** [comment]
Gah, sorry,
I'm still rapidly committing at the moment, so there may be some kinks. (Publishing is easier than testing locally in my setup.. -.-)

I'll patch it up soon.

**Comment by gregorianisch** [comment]
@jarekwg  No problem :) Thanks for fast reaction!

**Comment by jarekwg** [comment]
@gregorianisch I believe it's fixed now.

Cheers,

**Comment by gregorianisch** [comment]
@jarekwg Thanks! Working correctly :)
