### ISSUE TITLE
Uppercase letters breaks search bar.

### ISSUE THREAD

**Issue by gregorianisch** [ABASystems/react-keyed-file-browser#8]
Hi,

there is a bug with search bar. 

**Steps to reproduce:**
1 - Create an image, the name must contain lower and uppercase letters.
2 - Search for the added image through "Filter files" searchbar.

**Result:**
As soon as the uppercase letter is added to the search: 'No files matching"search result".' message is shown

**Expected result:**
Uppercase lettest should be implemented in the search.

**Comment by jarekwg** [comment]
Thanks, fixed in: 90abdbea4b0a39ae9a0993f14d681b935e7bb871
